// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb7CgfMWvQTpgfEB26DBcA03xdhylMEyw',
    appId: '1:674838629848:web:b2de4672ffc6a1927f76ad',
    messagingSenderId: '674838629848',
    projectId: 'flutter-sidekick-project',
    authDomain: 'flutter-sidekick-project.firebaseapp.com',
    storageBucket: 'flutter-sidekick-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZCwvVhz4SaAJewq4lmAecNaSZa_m2qnY',
    appId: '1:674838629848:android:542169e5680f8a6a7f76ad',
    messagingSenderId: '674838629848',
    projectId: 'flutter-sidekick-project',
    storageBucket: 'flutter-sidekick-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVkS59MZt0P1gA1-iNZ1-ljFstdvPoFWI',
    appId: '1:674838629848:ios:35d996c7ca253e337f76ad',
    messagingSenderId: '674838629848',
    projectId: 'flutter-sidekick-project',
    storageBucket: 'flutter-sidekick-project.appspot.com',
    iosClientId: '674838629848-4ilgc63nmum99n61vfn4tp1ep5b3kna0.apps.googleusercontent.com',
    iosBundleId: 'co.sidekick.sidekick',
  );
}
